# Function to display all keybindings organized by category with descriptions.
# Usage:
#   keybindings_cheat_sheet
function keybindings_cheat_sheet --description "Display all keybindings with descriptions"
    echo ""
    echo "⌨️  KEYBOARD LAYOUT:"
    echo "  Physical keys:    KEY 1 (left)  │  KEY 2 (middle)  │  KEY 3 (right)"
    echo "  ─────────────────────────────────────────────────────────────────"
    echo "  Internal:         fn/Globe      │  Control         │  Option"
    echo "  External:         CTRL          │  SUPER           │  ALT"
    echo ""
    echo "  KEY USAGE:"
    echo "    Key 1 → In-app shortcuts"
    echo "    Key 2 → Open applications & system actions"
    echo "    Key 3 → Window tiling & workspace management"
    echo ""
    echo "  SPECIAL MAPPINGS:"
    echo "    Right Shift → Delete"
    echo "    § → ~"
    echo ""

    # Window Management.
    echo "🪟  WINDOW MANAGEMENT:"
    echo "  - Key 3 + SHIFT + T              Toggle floating/tiling"
    echo "  - Key 3 + SHIFT + F              Toggle fullscreen"
    echo "  - Key 3 + R                      Rotate layout"
    echo "  - Key 3 + H/J/K/L                Focus left/down/up/right"
    echo "  - Key 3 + SHIFT + H/J/K/L        Move window"
    echo "  - Key 3 + SHIFT + ↑↓←→           Join with window"
    echo "  - Key 3 + SHIFT + -/+            Resize window"
    echo ""

    # Workspace Management.
    echo "📦 WORKSPACE MANAGEMENT:"
    echo "  - Key 3 + 1-9                   Switch workspace 1-9"
    echo "  - Key 3 + 0                     Switch workspace 10"
    echo "  - Key 3 + ←/→                   Previous/next workspace"
    echo "  - Key 3 + SHIFT + 1-9           Move window to workspace 1-9"
    echo "  - Key 3 + SHIFT + 0             Move window to workspace 10"
    echo "  - Key 3 + SHIFT + Tab           Move workspace to next monitor"
    echo "  - Key 3 + Tab                   Cycle through active applications"
    echo ""

    # Applications.
    echo "🚀 APPLICATIONS:"
    echo "  - Key 2 + B                      Google Chrome"
    echo "  - Key 2 + E                      Visual Studio Code"
    echo "  - Key 2 + I                      Docker daemon"
    echo "  - Key 2 + M                      Spotify"
    echo "  - Key 2 + K                      Obsidian"
    echo "  - Key 2 + /                      Gemini"
    echo "  - Key 2 + ;                      WezTerm"
    echo "  - Key 2 + ~                      Finder"
    echo "  - Key 2 + '                      System Settings"
    echo "  - Key 2 + SHIFT + A              1Password Autofill"
    echo "  - Key 2 + SHIFT + S              1Password Quick Access"
    echo "  - Key 2 + SHIFT + V              Maccy"
    echo "  - Key 2 + SHIFT + X              Flameshot Screenshot"
    echo "  - Key 2 + SHIFT + B              Screen Recording"
    echo ""

    # System Actions.
    echo "⚙️  SYSTEM ACTIONS"
    echo "  - Key 2 + Space                  Switch input source"
    echo "  - Key 2 + .                      Spotlight search"
    echo "  - Key 2 + \\                      Lock screen"
    echo "  - Key 2 + -                      Sleep"
    echo "  - Key 2 + Esc                    Shutdown"
    echo "  - Key 2 + ]                      Restart"
    echo "  - Key 3 + ,                      Reveal hidden menu bar icons"
    echo "  - Key 3 + .                      Hide hidden menu bar icons"
    echo "  - Key 3 + M                      Show frontmost app's menu titles"
    echo ""

    # Service Mode.
    echo "🔧 SERVICE MODE:"
    echo "     First, press Key 3 + ; to enter and then choose:"
    echo "  - R                             Reload environment"
    echo "  - Backspace                     Close all except current"
    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
end
