# Shell configuration abbreviations.
abbr efa "code ~/.config/fish/conf.d"
abbr efc "code ~/.config/fish/config.fish"
abbr eff "code ~/.config/fish/functions"

# System abbreviations.
abbr sm "btm"
abbr ff "fastfetch"
abbr kbcs "keybindings_cheat_sheet"
abbr alcs "aliases_cheat_sheet"
abbr us "brew update && brew upgrade && brew upgrade --cask && brew cleanup && mas upgrade && mo update"
abbr cs "mo clean && mo optimize"
abbr pi "brew install"
abbr pr "mo uninstall"
abbr ip "printf 'IPv4 (en0): %s\n' $(ipconfig getifaddr en0)"
abbr ks "sudo killall coreaudiod bluetoothd bluetoothaudiod"
abbr wrip "witr --port"
abbr wpi "witr --pid"
abbr ado "defaults write com.apple.sharingd DiscoverableMode -string 'Everyone' && killall sharingd"
abbr adc "defaults write com.apple.sharingd DiscoverableMode -string 'Off' && killall sharingd"
abbr po "sudo shutdown -h now"
abbr zzz "sudo pmset sleepnow"

# Terminal tools abbreviations.
abbr cat "bat"
abbr ls "eza --long --all --icons --color=always --group-directories-first --git"
abbr eva "calc"
abbr cd "z"
abbr cl "clear"
abbr fd "find"
abbr sed "sd"
abbr mkdir "mkdir -p"
abbr jsn "jless"
abbr hlx "hx"
abbr h "atuin history list"
abbr hs "atuin search -i"
abbr cl "clear"
abbr rmdp "keep_best_file | xargs rm -v"
abbr dl "aria2c -x 10 "
abbr ct "gg"
abbr fm "spf"
abbr oc "opencode"

# `Git` abbreviations.
abbr egc "code ~/.gitconfig"
abbr g "git"
abbr gl "git log"
abbr gls "git_log_current_branch"
abbr gpl "git pull"
abbr gft "git fetch"
abbr gftpl "git fetch --all --prune && git pull --all --prune"
abbr gps "git push"
abbr gpsf "git push -f"
abbr ga "git add"
abbr gap "git add -p"
abbr gapl "git apply"
abbr gaplr "git apply -R"
abbr gc "git commit"
abbr gca "git commit --amend"
abbr gcp "git cherry-pick"
abbr gcpc "git_cherry_pick_commit"
abbr gcpa "git cherry-pick --abort"
abbr gst "git status"
abbr gd "git diff"
abbr gds "git diff --staged"
abbr gdsn "git diff --staged --name-only"
abbr gco "git checkout"
abbr gcob "git checkout -b"
abbr grstr "git restore"
abbr grstrs "git restore --staged"
abbr grstrss "git restore --staged -p"
abbr grstb "git fetch origin && git reset --hard origin/(git rev-parse --abbrev-ref HEAD)"
abbr grst1 "git reset HEAD~"
abbr grstlb "git reset --hard HEAD"
abbr gfrb "git_fetch_and_rebase"
abbr grb "git rebase -i --autosquash HEAD~"
abbr grba "git rebase --abort"
abbr grbc "git rebase --continue"
abbr grbs "git rebase --skip"
abbr gbr "git branch"
abbr gbrls "git_list_branches"
abbr gbrd "git branch -d"
abbr gbrdf "git branch -D"
abbr gbrr "git branch -m"
abbr gsts "git_stash"
abbr gstsl "git_stash_list"
abbr gstsa "git stash apply"
abbr gstsp "git stash pop"
abbr gstsd "git stash drop"
abbr gfx "git commit --fixup"
abbr gafx "git_auto_fix_up"
abbr grp "git prune && rm -rf ./.git/gc.log && git gc --prune=now && git remote prune origin"
abbr gmr "git revert -m 1"
abbr grc "git revert"
abbr gra "git revert --abort"
abbr gm "git_merge_to_default_branch"
abbr gsu "git_add_remote_branch"
abbr ghprs "github_pr_reviews"
abbr ghoprs "github_my_prs open"
abbr ghcprs "github_my_prs closed"
abbr ghprc "github_create_pr"
abbr gbs "git_blame_stats"

# `Docker` abbreviations.
abbr d "docker"
abbr dc "docker compose"
abbr dcu "docker compose up --build -d"
abbr dcd "docker compose down"
abbr de "docker compose exec --it /bin/bash"
abbr dcl "docker compose down -v --remove-orphans && echo y | docker system prune -a --volumes"

# Services abbreviations.
abbr sc "sudo launchctl"
abbr scsts "sudo launchctl list"
abbr sci "sudo launchctl print"
abbr scstr "sudo launchctl load"
abbr sce "sudo launchctl load -w"
abbr scstp "sudo launchctl unload"
abbr scd "sudo launchctl unload -w"
abbr scrr "sudo launchctl kickstart -k"

# Emulators abbreviations.
abbr des "disable_android_emulators_audio"

# `WezTerm` abbreviations.
abbr sprd "printf '\\033]1337;SetUserVar=%s=%s\\007' tab_color cmVk"
abbr sstg "printf '\\033]1337;SetUserVar=%s=%s\\007' tab_color eWVsbG93"
abbr sdvl "printf '\\033]1337;SetUserVar=%s=%s\\007' tab_color Z3JlZW4="
